	<?php



	// Factura electronica


	var TipoDTE = $("#TipoDTE").val();
	var Folio = $("#Folio").val();
	var FechaEmision = $("#FechaEmision").val();
	var FechaVencimiento = $("#FechaVencimiento").val(); //Solo aparece en factura electronica 33
	var IndicadorServicio = $("#IndicadorServicio").val(); //Solo aparece en boleta electronica 39 0 41
	var RutE = $("#RutE").val();
	var RazonSocialE = $("#RazonSocialE").val();
	var ActividadEconomica = $("#ActividadEconomica").val();
	var GiroBoletaE = $("#GiroBoletaE").val();
	var ComunaOrigenE = $("#ComunaOrigenE").val();
	var DireccionOrigen = $("#DireccionOrigen").val();
	var Telefono = $("#Telefono").val();
	var RutR = $("#RutR").val();
	var RazonSocialR = $("#RazonSocialR").val();
	var DireccionR = $("#DireccionR").val();
	var Ciudad = $("#Ciudad").val();
	var ComunaOrigenR = $("#ComunaOrigenR").val();
	var GiroR = $("#GiroR").val();
	var Contacto = $("#Contacto").val();
	var RutSolicitante = $("#RutSolicitante").val();
	var Patente = $("#Patente").val();
	var RutTransportista = $("#RutTransportista").val();
	var DireccionDestino = $("#DireccionDestino").val();
	var ComunaDestino = $("#ComunaDestino").val();
	var CiudadDestino = $("#CiudadDestino").val();
	var RutTransportista = $("#RutTransportista").val();
	var RutChofer = $("#RutChofer").val();
	var NombreChofer = $("#NombreChofer").val();
	var MontoTotal = $("#MontoTotal").val();
	var MontoExento = $("#MontoExento").val();
	var MontoNeto = $("#MontoNeto").val();
	var IVA = $("#IVA").val();
	var TasaIVA = $("#TasaIVA").val();
	var MontoTotal = $("#MontoTotal").val();
	var indicadorExento = $("#indicadorExento").val();
	var Nombre = $("#Nombre").val();
	var descripcion = $("#descripcion").val();
	var cantidad = $("#cantidad").val();
	var UnidadMedida = $("#UnidadMedida").val();
	var precio = $("#precio").val();
	var descuento = $("#descuento").val();
	var recargo = $("#recargo").val();
	var montoItem = $("#montoItem").val();
	var FechaDocumentoReferencia = $("#FechaDocumentoReferencia").val();
	var TipoDocumento = $("#TipoDocumento").val();
	var CodigoReferencia = $("#CodigoReferencia").val();
	var RazonReferencia = $("#RazonReferencia").val();
	var FolioReferencia = $("#FolioReferencia").val();
	var TipoMovimiento = $("#TipoMovimiento").val();
	var DescripcionRE = $("#DescripcionRE").val();
	var TipoValor = $("#TipoValor").val();
	var Valor = $("#Valor").val();
	var Rutcert = $("#Rutcert").val();
	var Clavecert = $("#Clavecert").val();
?>